services:

    ####################################################################################################################
    # lazy commands
    ####################################################################################################################

    # management

    command.job.start_build:
        parent: 'command.template'
        arguments: ['job:build', 'executor.build.start']
        configurator: ['Hal\Agent\Executor\Management\StartBuildCommand', 'configure']
    command.job.start_deploy:
        parent: 'command.template'
        arguments: ['job:release', 'executor.release.start']
        configurator: ['Hal\Agent\Executor\Management\StartReleaseCommand', 'configure']

    command.management.build.remove:
        parent: 'command.template'
        arguments: ['management:build:remove', 'executor.build.remove']
        configurator: ['Hal\Agent\Executor\Management\RemoveBuildCommand', 'configure']

    # job runners

    command.runner.build:
        parent: 'command.template'
        arguments: ['runner:build', 'executor.runner.build']
        configurator: ['Hal\Agent\Executor\Runner\BuildCommand', 'configure']
    command.runner.deploy:
        parent: 'command.template'
        arguments: ['runner:deploy', 'executor.runner.deploy']
        configurator: ['Hal\Agent\Executor\Runner\DeployCommand', 'configure']

    # workers - cron

    # command.worker.build:
    #     parent: 'command.template'
    #     arguments: ['worker:build', 'executor.worker.build']
    #     configurator: ['Hal\Agent\Executor\Worker\BuildCommand', 'configure']
    # command.worker.deploy:
    #     parent: 'command.template'
    #     arguments: ['worker:deploy', 'executor.worker.deploy']
    #     configurator: ['Hal\Agent\Executor\Worker\DeployCommand', 'configure']

    # shared

    command.template:
        class: 'Symfony\Component\Console\Command\Command'
        factory: ['@command.factory', 'build']

    command.factory:
        class: 'Hal\Agent\Command\HalCommandFactory'
        arguments: ['@service_container']

    ####################################################################################################################
    # commands
    ####################################################################################################################

    # management

    executor.build.remove:
        class: 'Hal\Agent\Executor\Management\RemoveBuildCommand'
        arguments:
            - '@doctrine.em'
            - '@utility.filesystem'
        calls:
            - ['setArchivePath', ['%path.archive%']]

    # jobs

    executor.build.start:
        class: 'Hal\Agent\Executor\Management\StartBuildCommand'
        arguments:
            - '@doctrine.em'
            - '@executor.runner.build'
            - '@hal.api'

    executor.release.start:
        class: 'Hal\Agent\Executor\Management\StartReleaseCommand'
        arguments:
            - '@doctrine.em'
            - '@executor.runner.deploy'
            - '@hal.api'

    # job runners

    executor.runner.build:
        class: 'Hal\Agent\Executor\Runner\BuildCommand'
        arguments:
            - '@logger.event'
            - '@build.resolver'
            - '@build.downloader'
            - '@build.configuration.reader'
            - '@build.builder'
            - '@build.packer'
            - '@build.mover'
            - '@utility.filesystem'
            - '@ssh.manager'
    executor.runner.deploy:
        class: 'Hal\Agent\Executor\Runner\DeployCommand'
        arguments:
            - '@logger.event'
            - '@push.resolver'
            - '@push.mover'
            - '@push.unpacker'
            - '@push.configuration.reader'
            - '@push.builder'
            - '@push.before.builder'
            - '@push.deployer'
            - '@push.after.builder'
            - '@utility.filesystem'

    # workers - cron

    # executor.worker.build:
    #     class: 'Hal\Agent\Executor\Worker\BuildCommand'
    #     arguments:
    #         - '@doctrine.em'
    #         - '@utility.process.builder'
    #         - '@mcp.logger'
    #         - '%root%'
    # executor.worker.deploy:
    #     class: 'Hal\Agent\Executor\Worker\DeployCommand'
    #     arguments:
    #         - '@doctrine.em'
    #         - '@utility.process.builder'
    #         - '@mcp.logger'
    #         - '%root%'
