services:

    deploy.resolver:
        class: 'Hal\Agent\Deploy\Resolver'
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Hal\Agent\Utility\EncryptedPropertyResolver'
            - '@Symfony\Component\Filesystem\Filesystem'
            - '%path.temp_workspace%'

    deploy.artifacter:
        class: 'Hal\Agent\Deploy\Artifacter'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '@Symfony\Component\Filesystem\Filesystem'
            - '@build.support.file_compression'
            - '%path.artifacts%'

    deploy.build_runner:
        class: 'Hal\Agent\JobRunner'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '@service_container'
            - '%build.platforms%'

    deploy.release_runner:
        class: 'Hal\Agent\JobRunner'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '@service_container'
            - '%deployment.platforms%'

    deploy.cleaner:
        class: 'Hal\Agent\Job\LocalCleaner'
        arguments:
            - '@Symfony\Component\Filesystem\Filesystem'

    ############################################################################
    # support for deploy platforms
    ############################################################################

    deploy.support.file_compression:
        class: 'Hal\Agent\Job\FileCompression'
        arguments:
            - '@Hal\Agent\Symfony\ProcessRunner'
            - '%timeout.filepacking%'

    deploy.support.aws_authenticator:
        class: 'Hal\Core\AWS\AWSAuthenticator'
        arguments:
            - '@Psr\Log\LoggerInterface'
            - '@deploy.support.credential_provider'
            - '@Aws\Sdk'

    deploy.support.credential_provider:
        class: 'Hal\Core\AWS\CredentialProvider'
        arguments:
            - '@Psr\Log\LoggerInterface'
            - '@Hal\Core\Crypto\Encryption'
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Aws\Sdk'
            - '%aws.use_host_credentials%'
        calls:
            - ['setHostCredentials', ['@aws.host_sdk_credential_provider']]

