services:

    deploy_platform.rsync:
        public: true
        class: 'Hal\Agent\Deploy\Rsync\RsyncDeployPlatform'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '@Hal\Agent\Deploy\Rsync\Steps\Configurator'
            - '@Hal\Agent\Deploy\Rsync\Steps\Verifier'
            - '@Hal\Agent\Deploy\Rsync\Steps\CommandRunner'
            - '@Hal\Agent\Deploy\Rsync\Steps\Deployer'

    ############################################################################
    # steps
    ############################################################################

    'Hal\Agent\Deploy\Rsync\Steps\Configurator':
        - '@Hal\Agent\Logger\EventLogger'
        - '%deploy.rsync.user%'

    'Hal\Agent\Deploy\Rsync\Steps\Verifier':
        - '@Hal\Agent\Logger\EventLogger'
        - '@Hal\Agent\Remoting\SSHSessionManager'
        - '@deploy.rsync.verify_remoter'

    'Hal\Agent\Deploy\Rsync\Steps\CommandRunner':
        - '@deploy.rsync.standard_remoter'

    'Hal\Agent\Deploy\Rsync\Steps\Deployer':
        - '@Hal\Agent\Logger\EventLogger'
        - '@Hal\Agent\Remoting\FileSyncManager'
        - '@Hal\Agent\Symfony\ProcessRunner'
        - '%timeout.push%'

    ############################################################################
    # support
    ############################################################################

    deploy.rsync.standard_remoter:
        class: 'Hal\Agent\Remoting\SSHProcess'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '@Hal\Agent\Remoting\SSHSessionManager'
            - '%timeout.deploy.serverCommand%'

    deploy.rsync.verify_remoter:
        class: 'Hal\Agent\Remoting\SSHProcess'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '@Hal\Agent\Remoting\SSHSessionManager'
            - '%timeout.standard%'
