services:

    deploy_platform.eb:
        public: true
        class: 'Hal\Agent\Deploy\ElasticBeanstalk\EBDeployPlatform'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '@Hal\Agent\Deploy\ElasticBeanstalk\Steps\Configurator'
            - '@Hal\Agent\Deploy\ElasticBeanstalk\Steps\Compressor'
            - '@deploy.eb.artifact_uploader'
            - '@Hal\Agent\Deploy\ElasticBeanstalk\Steps\HealthChecker'
            - '@Hal\Agent\Deploy\ElasticBeanstalk\Steps\Deployer'
            - '@Hal\Agent\Deploy\ElasticBeanstalk\Steps\DeploymentVerifier'

    ############################################################################
    # steps
    ############################################################################

    'Hal\Agent\Deploy\ElasticBeanstalk\Steps\Configurator':
        - '@deploy.support.aws_authenticator'
        - '@QL\MCP\Common\Clock'
        - '%hal.baseurl%'

    'Hal\Agent\Deploy\ElasticBeanstalk\Steps\Compressor':
        - '@deploy.eb.support_s3_compressor'

    deploy.eb.artifact_uploader:
        class: 'Hal\Agent\AWS\S3Uploader'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'

    'Hal\Agent\Deploy\ElasticBeanstalk\Steps\HealthChecker':
        - '@QL\MCP\Common\Clock'
        - '%date.timezone%'

    'Hal\Agent\Deploy\ElasticBeanstalk\Steps\Deployer':
        - '@Hal\Agent\Logger\EventLogger'

    'Hal\Agent\Deploy\ElasticBeanstalk\Steps\DeploymentVerifier':
        - '@Hal\Agent\Logger\EventLogger'
        - '@Hal\Agent\Deploy\ElasticBeanstalk\Steps\HealthChecker'
        - '@deploy.eb.support_waiter'
        - '%deploy.eb.waiter.additional_wait_seconds%'

    ############################################################################
    # support
    ############################################################################

    deploy.eb.support_s3_compressor:
        class: 'Hal\Agent\Deploy\S3\Steps\Compressor'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '@Symfony\Component\Filesystem\Filesystem'
            - '@deploy.support.file_compression'

    deploy.eb.support_waiter:
        class: 'Hal\Agent\Waiter\Waiter'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '%deploy.eb.waiter.interval%'
            - '%deploy.eb.waiter.max%'
