services:
    build.resolver:
        class: 'Hal\Agent\Build\Resolver'
        arguments:
            - '@doctrine.em'
            - '@encrypted.resolver'
        calls:
            - ['setLocalTempPath', ['%path.temp%']]
            - ['setArchivePath', ['%path.archive%']]

    build.downloader:
        class: 'Hal\Agent\Build\Downloader'
        arguments:
            - '@logger.event'
            - '@build.support.file_compression'
            - '@vcs'

    builder:
        class: 'Hal\Agent\Build\Builder'
        arguments:
            - '@logger.event'
            - '@service_container'
            - '%build.platforms%'

    build.artifacter:
        class: 'Hal\Agent\Build\Artifacter'
        arguments:
            - '@logger.event'
            - '@filesystem'
            - '@build.support.file_compression'

    build.cleaner:
        class: 'Hal\Agent\Build\Generic\LocalCleaner'
        arguments: ['@filesystem']

    ############################################################################
    # support for build platforms
    ############################################################################

    build.support.file_compression:
        class: 'Hal\Agent\Build\Generic\FileCompression'
        arguments:
            - '@process_runner'
            - '%timeout.filepacking%'

    build.support.aws_authenticator:
        class: 'Hal\Core\AWS\AWSAuthenticator'
        arguments:
            - '@logger'
            - '@build.support.credential_provider'
            - '@aws'

    build.support.credential_provider:
        class: 'Hal\Core\AWS\CredentialProvider'
        arguments:
            - '@logger'
            - '@encryption'
            - '@doctrine.em'
            - '@aws'
