services:

    deploy_platform.s3:
        public: true
        class: 'Hal\Agent\Deploy\S3\S3DeployPlatform'
        arguments:
            - '@logger.event'
            - '@deploy.s3.configurator'
            - '@deploy.s3.compressor'
            - '@deploy.s3.artifact_uploader'
            - '@deploy.s3.sync_uploader'

    ############################################################################
    # steps
    ############################################################################

    deploy.s3.configurator:
        class: 'Hal\Agent\Deploy\S3\Steps\Configurator'
        arguments:
            - '@deploy.support.aws_authenticator'
            - '@clock'

    deploy.s3.compressor:
        class: 'Hal\Agent\Deploy\S3\Steps\Compressor'
        arguments:
            - '@logger.event'
            - '@filesystem'
            - '@deploy.support.file_compression'

    deploy.s3.artifact_uploader:
        class: 'Hal\Agent\AWS\S3Uploader'
        arguments: ['@logger.event']

    deploy.s3.sync_uploader:
        class: 'Hal\Agent\Deploy\S3\Steps\SyncUploader'
        arguments: ['@deploy.s3.support_sync_filesync']

    ############################################################################
    # support
    ############################################################################

    deploy.s3.support_sync_filesync:
        class: 'Hal\Agent\Deploy\S3\FileSync'
        arguments:
            - '@utility.finder'
            - '@deploy.s3.support_sync_comparator'
            - '@deploy.s3.support_sync_batcher'
        calls:
            - ['withFlag', ['COMPARE_FILES']]
            - ['withFlag', ['REMOVE_EXTRA_FILES']]

    deploy.s3.support_sync_comparator:
        class: 'Hal\Agent\Deploy\S3\Comparator'

    deploy.s3.support_sync_batcher:
        class: 'Hal\Agent\AWS\S3Batcher'
