services:

    deploy_platform.rsync:
        class: 'Hal\Agent\Deploy\Rsync\RsyncDeployPlatform'
        arguments:
            - '@logger.event'
            - '@deploy.rsync.configurator'
            - '@deploy.rsync.verifier'
            - '@deploy.rsync.runner'
            - '@deploy.rsync.deployer'

    ############################################################################
    # steps
    ############################################################################

    deploy.rsync.configurator:
        class: 'Hal\Agent\Deploy\Rsync\Steps\Configurator'
        arguments:
            - '@logger.event'
            - '%deploy.rsync.user%'

    deploy.rsync.verifier:
        class: 'Hal\Agent\Deploy\Rsync\Steps\Verifier'
        arguments:
            - '@logger.event'
            - '@ssh.manager'
            - '@deploy.rsync.verify.remoter'

    deploy.rsync.runner:
        class: 'Hal\Agent\Deploy\Rsync\Steps\Runner'
        arguments: ['@deploy.rsync.standard.remoter']

    deploy.rsync.deployer:
        class: 'Hal\Agent\Deploy\Rsync\Steps\Deployer'
        arguments:
            - '@logger.event'
            - '@ssh.filemanager'
            - '@utility.process.builder'
            - '%timeout.push%'

    ############################################################################
    # support
    ############################################################################

    deploy.rsync.standard.remoter:
        class: 'Hal\Agent\Remoting\SSHProcess'
        arguments:
            - '@logger.event'
            - '@ssh.manager'
            - '%timeout.deploy.serverCommand%'

    deploy.rsync.verify.remoter:
        class: 'Hal\Agent\Remoting\SSHProcess'
        arguments:
            - '@logger.event'
            - '@ssh.manager'
            - '%timeout.standard%'
