services:

    deploy_platform.s3:
        class: 'Hal\Agent\Deploy\S3\S3DeployPlatform'
        arguments:
            - '@logger.event'
            - '@deploy.s3.configurator'
            - '@deploy.support.aws_authenticator'
            - '@deploy.s3.validator'
            - '@deploy.s3.compressor'
            - '@deploy.s3_artifact.uploader'
            - '@deploy.s3_sync.uploader'
            - '@deploy.s3_artifact.verifier'

    ############################################################################
    # steps
    ############################################################################

    deploy.s3.configurator:
        class: 'Hal\Agent\Deploy\S3\Steps\Configurator'
        arguments:
            - '@encryption'
            - '@clock'

    deploy.s3.validator:
        class: 'Hal\Agent\Deploy\S3\Steps\Validator'
        arguments:
            - '@utility.filesystem'
            - '@utility.process.builder'
            - '%timeout.deploy.serverCommand%'

    deploy.s3.compressor:
        class: 'Hal\Agent\Deploy\S3\Steps\Compressor'
        arguments: ['@build.support.file_compression']

    deploy.s3_artifact.uploader:
        class: 'Hal\Agent\Deploy\S3\Steps\ArtifactUploader'

    deploy.s3_sync.uploader:
        class: 'Hal\Agent\Deploy\S3\Steps\SyncUploader'
        arguments: ['@deploy.s3_sync.support.synchronizer']

    deploy.s3_artifact.verifier:
        class: 'Hal\Agent\Deploy\S3\Steps\ArtifactVerifier'

    ############################################################################
    # support
    ############################################################################

    deploy.s3_sync.support.synchronizer:
        class: 'Hal\Agent\Deploy\S3\Sync\SyncManager'
        arguments:
            - '@deploy.s3_sync.support.transferer'
            - '@deploy.s3_sync.support.deleter'
            - '@utility.finder'

    deploy.s3_sync.support.transferer:
        class: 'Hal\Agent\Deploy\S3\Sync\TransferManager'

    deploy.s3_sync.support.deleter:
        class: 'Hal\Agent\Deploy\S3\Sync\BatchDeleteManager'
