services:

    deploy_platform.s3:
        class: 'Hal\Agent\Deploy\S3\S3DeployPlatform'
        arguments:
            - '@logger.event'
            - '@deploy.support.aws_configurator'
            - '@deploy.s3.configurator'
            - '@service_container'
            - '%deploy.s3.strategies%'

    ############################################################################
    # subplatforms
    ############################################################################

    deploy_platform.s3.sync:
        class: 'Hal\Agent\Deploy\S3\Sync\S3SyncDeployPlatform'
        arguments:
            - '@logger.event'
            - '@deploy.support.aws_authenticator'
            - '@deploy.s3.validator'
            - '@deploy.s3_sync.uploader'

    # deploy_platform.s3.artifact:
        # class: 'Hal\Agent\Deploy\S3\Artifact\S3ArtifactDeployPlatform'
        # arguments:
            # - '@logger.event'
            # - '@deploy.support.aws_authenticator'
            # - '@deploy.s3.validator'
            # - '@deploy.s3_artifact.uploader'

    ############################################################################
    # steps
    ############################################################################

    deploy.s3.configurator:
        class: 'Hal\Agent\Deploy\S3\Steps\Configurator'
        arguments: ['@clock']

    deploy.s3.validator:
        class: 'Hal\Agent\Deploy\S3\Steps\Validator'
        arguments:
            - '@utility.filesystem'
            - '@utility.process.builder'
            - '%timeout.deploy.serverCommand%'

    deploy.s3_sync.uploader:
        class: 'Hal\Agent\Deploy\S3\Sync\Steps\Uploader'
        arguments: ['@deploy.s3_sync.support.synchronizer']

    deploy.s3_artifact.compressor:
        class: 'Hal\Agent\Deploy\S3\Artifact\Steps\Compressor'
        arguments:
            - '@logger.event'
            - '@utility.filesystem'
            - '@utility.process.builder'
            - '%timeout.deploy.serverCommand%'

    # deploy.s3_artifact.uploader:
        # class: 'Hal\Agent\Deploy\S3\Artifact\Steps\Uploader'

    ############################################################################
    # support
    ############################################################################

    deploy.s3_sync.support.synchronizer:
        class: 'Hal\Agent\Deploy\S3\Sync\Upload\SyncManager'
        arguments:
            - '@deploy.s3_sync.support.transferer'
            - '@deploy.s3_sync.support.deleter'
            - '@utility.finder'

    deploy.s3_sync.support.transferer:
        class: 'Hal\Agent\Deploy\S3\Sync\Upload\TransferManager'

    deploy.s3_sync.support.deleter:
        class: 'Hal\Agent\Deploy\S3\Sync\Upload\BatchDeleteManager'
