services:

    ############################################################################
    # platforms
    ############################################################################

    build_platform.linux:
        class: 'Hal\Agent\Build\Linux\LinuxBuildPlatform'
        arguments:
            - '@logger.event'
            - '@build.linux.configurator'
            - '@build.linux.exporter'
            - '@build.linux.docker_builder'
            - '@build.linux.importer'
            - '@build.linux.cleaner'
            - '@encrypted.resolver'
            - '%build.platforms.option.linux.docker_default_image%'

    ############################################################################
    # builders
    ############################################################################

    build.linux.docker_builder:
        class: 'Hal\Agent\Build\Linux\DockerBuilder'
        arguments:
            - '@logger.event'
            - '@build.linux.support_dockerinator'
            - '@build.linux.support_docker_validator'
            - '@job_configuration.step_parser'

    ############################################################################
    # steps
    ############################################################################

    build.linux.configurator:
        class: 'Hal\Agent\Build\Linux\Steps\Configurator'
        arguments:
            - '%path.linux_builder%'
            - '%build.linux.user%'
            -
                - '%build.linux.server%'

    build.linux.exporter:
        class: 'Hal\Agent\Build\Linux\Steps\Exporter'
        arguments:
            - '@ssh.manager'
            - '@build.support.file_compression'

    build.linux.importer:
        class: 'Hal\Agent\Build\Linux\Steps\Importer'
        arguments:
            - '@ssh.manager'
            - '@build.support.file_compression'
            - '@utility.filesystem'

    build.linux.cleaner:
        class: 'Hal\Agent\Build\Linux\Steps\Cleaner'
        arguments: ['@build.linux.support_remoter']

    ############################################################################
    # support
    ############################################################################

    build.linux.support_remoter:
        class: 'Hal\Agent\Remoting\SSHProcess'
        arguments:
            - '@logger.event'
            - '@ssh.manager'
            - '%timeout.linux_builder_internal%'

    build.linux.support_build_remoter:
        class: 'Hal\Agent\Remoting\SSHProcess'
        arguments:
            - '@logger.event'
            - '@ssh.manager'
            - '%timeout.build%'

    ############################################################################
    # support - docker
    ############################################################################

    build.linux.support_dockerinator:
        class: 'Hal\Agent\Docker\LinuxDockerinator'
        arguments:
            - '@logger.event'
            - '@build.linux.support_remoter'
            - '@build.linux.support_build_remoter'
            - '%build.platforms.option.manual_dns%'
        calls:
            - ['setBuilderDebugLogging', ['%error_handling.docker.debug%']]

    build.linux.support_docker_validator:
        class: 'Hal\Agent\Docker\DockerImageValidator'
        arguments:
            - '@logger.event'
            - '%build.platforms.option.linux.allowed_images%'
            - '%build.platforms.option.linux.docker_easy_repo%'
            - '%build.platforms.option.linux.docker_private_registry%'
