services:

    deploy_platform.eb:
        class: 'Hal\Agent\Deploy\ElasticBeanstalk\EBDeployPlatform'
        arguments:
            - '@logger.event'
            - '@deploy.eb.configurator'
            - '@deploy.eb.compressor'
            - '@deploy.eb.artifact_uploader'
            - '@deploy.eb.healthchecker'
            - '@deploy.eb.deployer'
            - '@deploy.eb.verifier'

    ############################################################################
    # steps
    ############################################################################

    deploy.eb.configurator:
        class: 'Hal\Agent\Deploy\ElasticBeanstalk\Steps\Configurator'
        arguments:
            - '@deploy.support.aws_authenticator'
            - '@clock'
            - '%hal.baseurl%'

    deploy.eb.compressor:
        class: 'Hal\Agent\Deploy\ElasticBeanstalk\Steps\Compressor'
        arguments:
            - '@deploy.s3.compressor'

    deploy.eb.artifact_uploader:
        class: 'Hal\Agent\AWS\S3Uploader'

    deploy.eb.healthchecker:
        class: 'Hal\Agent\Deploy\ElasticBeanstalk\Steps\HealthChecker'
        arguments:
            - '@clock'
            - '%date.timezone%'

    deploy.eb.deployer:
        class: 'Hal\Agent\Deploy\ElasticBeanstalk\Steps\Deployer'
        arguments:
            - '@logger.event'

    deploy.eb.verifier:
        class: 'Hal\Agent\Deploy\ElasticBeanstalk\Steps\DeploymentVerifier'
        arguments:
            - '@logger.event'
            - '@deploy.eb.healthchecker'
            - '@deploy.eb.waiter'
            - '%deploy.eb.waiter.additionalWaitTimeSeconds%'

    ############################################################################
    # support
    ############################################################################

    deploy.eb.waiter:
        class: 'Hal\Agent\Waiter\Waiter'
        arguments:
            - '@logger.event'
            - '%deploy.eb.waiter.interval%'
            - '%deploy.eb.waiter.max%'
