services:

    deploy_platform.script:
        class: 'Hal\Agent\Deploy\Script\ScriptDeployPlatform'
        arguments:
            - '@logger.event'
            - '@deploy.script.configurator'
            - '@build.build_runner'

    ############################################################################
    # steps
    ############################################################################

    deploy.script.configurator:
        class: 'Hal\Agent\Deploy\Script\Steps\Configurator'

