services:

    deploy_platform.eb:
        class: 'Hal\Agent\Push\ElasticBeanstalk\Deployer'
        arguments:
            - '@logger.event'
            - '@deploy.support.aws_authenticator'
            - '@push.eb.healthchecker'
            - '@deploy.support.packer'
            - '@push.eb.uploader'
            - '@push.eb.pusher'

    ############################################################################
    # support
    ############################################################################

    push.eb.healthchecker:
        class: 'Hal\Agent\Push\ElasticBeanstalk\HealthChecker'
        arguments:
            - '@clock'
            - '%date.timezone%'

    push.eb.uploader:
        class: 'Hal\Agent\Push\ElasticBeanstalk\Uploader'
        arguments: ['@logger.event']
        calls:
            - ['allowOverwrite', [false]]

    push.eb.pusher:
        class: 'Hal\Agent\Push\ElasticBeanstalk\Pusher'
        arguments:
            - '@logger.event'
            - '@push.eb.healthchecker'
            - '@push.eb.waiter'

    push.eb.waiter:
        class: 'Hal\Agent\Waiter\Waiter'
        arguments: ['%push.eb.waiter.interval%', '%push.eb.waiter.max%']
