services:

    deploy_platform.cd:
        class: 'Hal\Agent\Deploy\CodeDeploy\CodeDeployDeployPlatform'
        arguments:
            - '@logger.event'
            - '@deploy.cd.configurator'
            - '@deploy.cd.verifier'
            - '@deploy.cd.compressor'
            - '@deploy.cd.uploader'
            - '@deploy.cd.deployer'

    ############################################################################
    # steps
    ############################################################################

    deploy.cd.configurator:
        class: 'Hal\Agent\Deploy\CodeDeploy\Steps\Configurator'
        arguments:
            - '@logger.event'
            - '@clock'
            - '@deploy.support.aws_authenticator'
            - '%hal.baseurl%'

    deploy.cd.verifier:
        class: 'Hal\Agent\Deploy\CodeDeploy\Steps\Verifier'
        arguments:
            - '@logger.event'
            - '@deploy.cd.healthchecker'
            - '@deploy.cd.waiter'
            - '@deploy.cd.deploywaiter'

    deploy.cd.compressor:
        class: 'Hal\Agent\Deploy\CodeDeploy\Steps\Compressor'
        arguments: ['@deploy.s3.compressor']

    deploy.cd.uploader:
        class: 'Hal\Agent\Deploy\CodeDeploy\Steps\Uploader'
        arguments:
            - '@logger.event'
            - '@deploy.s3.artifact_uploader'

    deploy.cd.deployer:
        class: 'Hal\Agent\Deploy\CodeDeploy\Steps\Deployer'
        arguments:
            - '@logger.event'

    ############################################################################
    # support
    ############################################################################

    deploy.cd.deploywaiter:
        class: 'Hal\Agent\Deploy\CodeDeploy\CodeDeployWaiter'
        arguments:
            - '@logger.event'
            - '@deploy.cd.healthchecker'

    deploy.cd.waiter:
        class: 'Hal\Agent\Waiter\Waiter'
        arguments:
            - '%deploy.cd.waiter.interval%'
            - '%deploy.cd.waiter.max%'

    deploy.cd.healthchecker:
        class: 'Hal\Agent\AWS\CodeDeployHealthChecker'
        arguments:
            - '@clock'
            - '%date.timezone%'

