services:
# unix
    build.unix.handler:
        class: 'Hal\Agent\Build\Linux\LinuxBuildPlatform'
        arguments:
            - '@logger.event'
            - '@build.linux_configurator'
            - '@build.linux_exporter'
            - '@build.linux_builder'
            - '@build.linux_importer'
            - '@build.linux_cleaner'
            - '@encrypted.resolver'
            - '%build.platforms.option.docker.default_image%'

    ############################################################################

    build.linux_configurator:
        class: 'Hal\Agent\Build\Linux\Steps\Configurator'
        arguments:
            - '%path.linux_builder%'
            - '%build.linux.user%'
            -
                - '%build.linux.server%'

    build.linux_exporter:
        class: 'Hal\Agent\Build\Linux\Steps\Exporter'
        arguments:
            - '@ssh.manager'
            - '@build.support.file_compression'

    build.linux_builder:
        class: 'Hal\Agent\Build\Linux\DockerBuilder'
        arguments:
            - '@logger.event'
            - '@build.support.linux_remoter'
            - '@build.support.linux_build_remoter'
            - '@build.support.linux_filetransfer_remoter'
            - '%path.linux_dockerfiles%'
        calls:
            - ['setBuilderDebugLogging', ['%error_handling.docker.debug%']]

    build.linux_importer:
        class: 'Hal\Agent\Build\Linux\Steps\Importer'
        arguments:
            - '@ssh.manager'
            - '@build.support.file_compression'
            - '@utility.filesystem'

    build.linux_cleaner:
        class: 'Hal\Agent\Build\Linux\Steps\Cleaner'
        arguments: ['@build.support.linux_remoter']

    ############################################################################

    build.support.linux_remoter:
        class: 'Hal\Agent\Remoting\SSHProcess'
        arguments:
            - '@logger.event'
            - '@ssh.manager'
            - '%timeout.standard%'

    build.support.linux_build_remoter:
        class: 'Hal\Agent\Remoting\SSHProcess'
        arguments:
            - '@logger.event'
            - '@ssh.manager'
            - '%timeout.build%'

    build.support.linux_filetransfer_remoter:
        class: 'Hal\Agent\Remoting\SSHProcess'
        arguments:
            - '@logger.event'
            - '@ssh.manager'
            - '%timeout.filetransfer%'
