services:

    deploy_platform.s3:
        public: true
        class: 'Hal\Agent\Deploy\S3\S3DeployPlatform'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '@Hal\Agent\Deploy\S3\Steps\Configurator'
            - '@Hal\Agent\Deploy\S3\Steps\Compressor'
            - '@Hal\Agent\AWS\S3Uploader'
            - '@Hal\Agent\Deploy\S3\Steps\SyncUploader'

    ############################################################################
    # steps
    ############################################################################

    'Hal\Agent\Deploy\S3\Steps\Configurator':
        - '@deploy.support.aws_authenticator'
        - '@QL\MCP\Common\Clock'

    'Hal\Agent\Deploy\S3\Steps\Compressor':
        - '@Hal\Agent\Logger\EventLogger'
        - '@Symfony\Component\Filesystem\Filesystem'
        - '@deploy.support.file_compression'

    'Hal\Agent\AWS\S3Uploader':
        - '@Hal\Agent\Logger\EventLogger'

    'Hal\Agent\Deploy\S3\Steps\SyncUploader':
        - '@Hal\Agent\Deploy\S3\FileSync'

    ############################################################################
    # support
    ############################################################################

    'Hal\Agent\Deploy\S3\FileSync':
        arguments:
            - '@deploy.s3.support_finder'
            - '@Hal\Agent\Deploy\S3\Comparator'
            - '@Hal\Agent\AWS\S3Batcher'
        calls:
            - ['withFlag', ['COMPARE_FILES']]
            - ['withFlag', ['REMOVE_EXTRA_FILES']]

    'Hal\Agent\Deploy\S3\Comparator': []

    'Hal\Agent\AWS\S3Batcher': []

    deploy.s3.support_finder:
        class: 'Symfony\Component\Finder\Finder'
