services:

    deploy_platform.cd:
        public: true
        class: 'Hal\Agent\Deploy\CodeDeploy\CodeDeployDeployPlatform'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '@Hal\Agent\Deploy\CodeDeploy\Steps\Configurator'
            - '@Hal\Agent\Deploy\CodeDeploy\Steps\Verifier'
            - '@Hal\Agent\Deploy\CodeDeploy\Steps\Compressor'
            - '@deploy.cd.artifact_uploader'
            - '@Hal\Agent\Deploy\CodeDeploy\Steps\Deployer'

    ############################################################################
    # steps
    ############################################################################

    'Hal\Agent\Deploy\CodeDeploy\Steps\Configurator':
        - '@Hal\Agent\Logger\EventLogger'
        - '@QL\MCP\Common\Clock'
        - '@deploy.support.aws_authenticator'
        - '%hal.baseurl%'

    'Hal\Agent\Deploy\CodeDeploy\Steps\Verifier':
        - '@Hal\Agent\Logger\EventLogger'
        - '@Hal\Agent\AWS\CodeDeployHealthChecker'
        - '@deploy.cd.support_waiter'
        - '@Hal\Agent\Deploy\CodeDeploy\CodeDeployWaiter'

    'Hal\Agent\Deploy\CodeDeploy\Steps\Compressor':
        - '@deploy.cd.support_s3_compressor'

    deploy.cd.artifact_uploader:
        class: 'Hal\Agent\AWS\S3Uploader'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'

    'Hal\Agent\Deploy\CodeDeploy\Steps\Deployer':
        - '@Hal\Agent\Logger\EventLogger'

    ############################################################################
    # support
    ############################################################################

    'Hal\Agent\Deploy\CodeDeploy\CodeDeployWaiter':
        - '@Hal\Agent\Logger\EventLogger'
        - '@Hal\Agent\AWS\CodeDeployHealthChecker'

    'Hal\Agent\AWS\CodeDeployHealthChecker':
        - '@QL\MCP\Common\Clock'
        - '%date.timezone%'

    deploy.cd.support_s3_compressor:
        class: 'Hal\Agent\Deploy\S3\Steps\Compressor'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '@Symfony\Component\Filesystem\Filesystem'
            - '@deploy.support.file_compression'

    deploy.cd.support_waiter:
        class: 'Hal\Agent\Waiter\Waiter'
        arguments:
            - '%deploy.cd.waiter.interval%'
            - '%deploy.cd.waiter.max%'
