services:
    build.resolver:
        class: 'Hal\Agent\Build\Resolver'
        arguments:
            - '@doctrine.em'
            - '@utility.environment.resolver'
            - '@encrypted.resolver'
        calls:
            - ['setLocalTempPath', ['%path.temp%']]
            - ['setArchivePath', ['%path.archive%']]

    build.downloader:
        class: 'Hal\Agent\Build\Downloader'
        arguments:
            - '@logger.event'
            - '@build.support.file_compression'
            - '@vcs'

    build.configuration_reader:
        class: 'Hal\Agent\Build\ConfigurationReader'
        arguments:
            - '@logger.event'
            - '@utility.filesystem'
            - '@yaml.parser'

    build.builder:
        class: 'Hal\Agent\Build\DelegatingBuilder'
        arguments:
            - '@logger.event'
            - '@service_container'
            - '%build.platforms%'
        calls:
            - ['enableStaging', []]

    build.artifacter:
        class: 'Hal\Agent\Build\Artifacter'
        arguments:
            - '@logger.event'
            - '@utility.filesystem'
            - '@build.support.file_compression'

    build.cleaner:
        class: 'Hal\Agent\Build\Generic\LocalCleaner'
        arguments: ['@utility.filesystem']


    build.support.file_compression:
        class: 'Hal\Agent\Build\Generic\FileCompression'
        arguments:
            - '@logger.event'
            - '@utility.process.builder'
            - '%timeout.filepacking%'
