services:

    ############################################################################
    # platforms
    ############################################################################

    build_platform.linux:
        public: true
        class: 'Hal\Agent\Build\Linux\LinuxBuildPlatform'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '@Hal\Agent\Utility\EncryptedPropertyResolver'
            - '@Hal\Agent\Build\Linux\Steps\Configurator'
            - '@Hal\Agent\Build\Linux\Steps\Exporter'
            - '@Hal\Agent\Build\Linux\DockerBuilder'
            - '@Hal\Agent\Build\Linux\Steps\Importer'
            - '%build.platforms.option.linux.docker_default_image%'

    ############################################################################
    # builders
    ############################################################################

    'Hal\Agent\Build\Linux\DockerBuilder':
        - '@Hal\Agent\Logger\EventLogger'
        - '@Hal\Agent\Docker\LinuxDockerinator'
        - '@build.linux.support_docker_validator'
        - '@build.support.file_compression'
        - '@Hal\Agent\JobConfiguration\StepParser'

    ############################################################################
    # steps
    ############################################################################

    'Hal\Agent\Build\Linux\Steps\Configurator': []

    'Hal\Agent\Build\Linux\Steps\Exporter':
        - '@Symfony\Component\Filesystem\Filesystem'

    'Hal\Agent\Build\Linux\Steps\Importer':
        - '@Symfony\Component\Filesystem\Filesystem'

    ############################################################################
    # support - docker
    ############################################################################

    'Hal\Agent\Docker\LinuxDockerinator':
        arguments:
            - '@Hal\Agent\Symfony\ProcessRunner'
            - '%timeout.internal_build_steps%'
            - '%timeout.build_steps%'
            - '%build.platforms.option.manual_dns%'
        calls:
            - ['setBuilderDebugLogging', ['%error_handling.docker.debug%']]

    build.linux.support_docker_validator:
        class: 'Hal\Agent\Docker\DockerImageValidator'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '%build.platforms.option.linux.allowed_images%'
            - '%build.platforms.option.linux.docker_easy_repo%'
            - '%build.platforms.option.linux.docker_private_registry%'
