services:

    deploy_platform.script:
        public: true
        class: 'Hal\Agent\Deploy\Script\ScriptDeployPlatform'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '@Hal\Agent\Deploy\Script\Steps\Configurator'
            - '@build.build_runner'

    ############################################################################
    # steps
    ############################################################################

    'Hal\Agent\Deploy\Script\Steps\Configurator': []

