services:

    deploy_platform.eb:
        public: true
        class: 'Hal\Agent\Deploy\ElasticBeanstalk\ELBDeployPlatform'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '@Hal\Agent\Deploy\ElasticLoadBalancer\Steps\Configurator'
            - '@Hal\Agent\Deploy\ElasticLoadBalancer\Steps\HealthChecker'
            - '@Hal\Agent\Deploy\ElasticLoadBalancer\Steps\EC2Finder'
            - '@Hal\Agent\Deploy\ElasticLoadBalancer\Steps\Swapper'
            - '@Hal\Agent\Deploy\ElasticLoadBalancer\Steps\ELBManager'

    ############################################################################
    # steps
    ############################################################################

    'Hal\Agent\Deploy\ElasticLoadBalancer\Steps\Configurator':
        - '@deploy.support.aws_authenticator'

    'Hal\Agent\Deploy\ElasticLoadBalancer\Steps\HealthChecker':
        - '@Hal\Agent\Logger\EventLogger'

    'Hal\Agent\Deploy\ElasticLoadBalancer\Steps\EC2Finder':
        - '@Hal\Agent\Logger\EventLogger'

    'Hal\Agent\Deploy\ElasticLoadBalancer\Steps\Swapper':
        - '@Hal\Agent\Logger\EventLogger'
        - '@deploy.elb.support_waiter'

    'Hal\Agent\Deploy\ElasticLoadBalancer\Steps\ELBManager':
        - '@Hal\Agent\Logger\EventLogger'

    ############################################################################
    # support
    ############################################################################

    deploy.elb.support_waiter:
        class: 'Hal\Agent\Waiter\Waiter'
        arguments:
            - '@Hal\Agent\Logger\EventLogger'
            - '%deploy.eb.waiter.interval%'
            - '%deploy.eb.waiter.max%'
