services:

    deploy.resolver:
        class: 'Hal\Agent\Push\Resolver'
        arguments:
            - '@logger.event'
            - '@doctrine.em'
            - '@clock'
            - '@encrypted.resolver'
            - '%deploy.rsync.user%'
        calls:
            - ['setLocalTempPath', ['%path.temp%']]
            - ['setArchivePath', ['%path.archive%']]

    deploy.mover:
        class: 'Hal\Agent\Push\Mover'
        arguments: ['@logger.event', '@utility.filesystem']

    deploy.unpacker:
        class: 'Hal\Agent\Push\Unpacker'
        arguments:
            - '@logger.event'
            - '@utility.process.builder'
            - '@utility.filesystem'
            - '@yaml.dumper'
            - '%timeout.filepacking%'

    deploy.builder:
        class: 'Hal\Agent\Build\BuildPlatform'
        arguments:
            - '@logger.event'
            - '@service_container'
            - '%build.platforms%'

    deployer:
        class: 'Hal\Agent\Push\DelegatingDeployer'
        arguments:
            - '@logger.event'
            - '@service_container'
            - '%deployment.platforms%'

    ############################################################################
    # support for deploy platforms
    ############################################################################

    deploy.support.packer:
        class: 'Hal\Agent\Push\ReleasePacker'
        arguments:
            - '@logger.event'
            - '@utility.filesystem'
            - '@utility.process.builder'
            - '%timeout.filepacking%'

    deploy.support.mover:
        class: 'Hal\Agent\Push\Mover'
        arguments: ['@logger.event', '@utility.filesystem']

    deploy.support.aws_authenticator:
        class: 'Hal\Core\AWS\AWSAuthenticator'
        arguments:
            - '@logger'
            - '@deploy.support.credential_provider'
            - '@aws'

    deploy.support.credential_provider:
        class: 'Hal\Core\AWS\CredentialProvider'
        arguments:
            - '@logger'
            - '@encryption'
            - '@doctrine.em'
            - '@aws'

    yaml.dumper:
        class: 'Symfony\Component\Yaml\Dumper'
        calls:
            - ['setIndentation', ['4']]
