services:
    ####################################################################################################################
    # GITHUB
    ####################################################################################################################

    github.archive:
        class: 'Hal\Agent\Github\ArchiveApi'
        arguments: ['@github.archive_guzzle', '%github.baseurl.api%']

    github.archive_guzzle:
        class: 'GuzzleHttp\Client'
        arguments:
            -
                headers:
                    Authorization: 'token %github.token%'


    ####################################################################################################################
    # GITHUB SDK
    ####################################################################################################################
    # @todo add caching like in UI

    github.client:
        class: 'Github\Client'
        arguments:
            - '@github.http.builder'
            - null
            - '%github.baseurl.site%'
        calls:
            - ['authenticate', ['%github.token%', null, 'http_token']]

    github.references:
        class: 'Github\Api\GitData\References'
        arguments: ['@github.client']

    github.commits:
        class: 'Github\Api\Repository\Commits'
        arguments: ['@github.client']

    github.pullRequests:
        class: 'Github\Api\PullRequest'
        arguments: ['@github.client']

    # http
    github.http.builder:
        class: 'Github\HttpClient\Builder'
        arguments: ['@github.http.guzzle_adapter']

    github.http.guzzle_adapter:
        class: 'Http\Adapter\Guzzle6\Client'
        arguments: ['@github.http.guzzle']

    github.http.guzzle:
        class: 'GuzzleHttp\Client'
