services:

    push.resolver:
        class: 'Hal\Agent\Push\Resolver'
        arguments:
            - '@logger.event'
            - '@doctrine.em'
            - '@clock'
            - '@utility.environment.resolver'
            - '@encrypted.resolver'
            - '%deploy.rsync.user%'
            - '%github.baseurl.site%'
        calls:
            - ['setLocalTempPath', ['%path.temp%']]
            - ['setArchivePath', ['%path.archive%']]

    push.mover:
        class: 'Hal\Agent\Push\Mover'
        arguments: ['@logger.event', '@utility.filesystem']

    push.unpacker:
        class: 'Hal\Agent\Push\Unpacker'
        arguments:
            - '@logger.event'
            - '@utility.process.builder'
            - '@utility.filesystem'
            - '@yaml.dumper'
            - '%timeout.filepacking%'

    push.packer:
        class: 'Hal\Agent\Push\ReleasePacker'
        arguments:
            - '@logger.event'
            - '@utility.filesystem'
            - '@utility.process.builder'
            - '%timeout.filepacking%'

    push.configuration.reader:
        class: 'Hal\Agent\Build\ConfigurationReader'
        arguments:
            - '@logger.event'
            - '@utility.filesystem'
            - '@yaml.parser'

    push.builder:
        class: 'Hal\Agent\Build\DelegatingBuilder'
        arguments:
            - '@logger.event'
            - '@service_container'
            - '%build.platforms%'

    push.deployer:
        class: 'Hal\Agent\Push\DelegatingDeployer'
        arguments:
            - '@logger.event'
            - '@service_container'
            - '%deployment.platforms%'

    ####################################################################################################################
    # eb
    ####################################################################################################################

    push.eb.deployer:
        class: 'Hal\Agent\Push\ElasticBeanstalk\Deployer'
        arguments:
            - '@logger.event'
            - '@push.aws.authenticator'
            - '@push.eb.healthchecker'
            - '@push.packer'
            - '@push.eb.uploader'
            - '@push.eb.pusher'

    push.eb.healthchecker:
        class: 'Hal\Agent\Push\ElasticBeanstalk\HealthChecker'
        arguments:
            - '@clock'
            - '%date.timezone%'

    push.eb.uploader:
        class: 'Hal\Agent\Push\ElasticBeanstalk\Uploader'
        arguments: ['@logger.event']
        calls:
            - ['allowOverwrite', [false]]

    push.eb.pusher:
        class: 'Hal\Agent\Push\ElasticBeanstalk\Pusher'
        arguments:
            - '@logger.event'
            - '@push.eb.healthchecker'
            - '@push.eb.waiter'

    push.eb.waiter:
        class: 'Hal\Agent\Waiter\Waiter'
        arguments: ['%push.eb.waiter.interval%', '%push.eb.waiter.max%']

    ####################################################################################################################
    # rsync
    ####################################################################################################################

    push.rsync.deployer:
        class: 'Hal\Agent\Push\Rsync\Deployer'
        arguments:
            - '@logger.event'
            - '@push.rsync.verify'
            - '@push.rsync.delta'
            - '@push.rsync.serverCommand'
            - '@push.rsync.pusher'

    push.rsync.verify:
        class: 'Hal\Agent\Push\Rsync\Verify'
        arguments:
            - '@logger.event'
            - '@ssh.manager'
            - '@push.rsync.verify.remoter'

    push.rsync.delta:
        class: 'Hal\Agent\Push\Rsync\CodeDelta'
        arguments:
            - '@logger.event'
            - '@push.rsync.delta.remoter'
            - '@yaml.parser'
            - '@github.commits'

    push.rsync.pusher:
        class: 'Hal\Agent\Push\Rsync\Pusher'
        arguments:
            - '@logger.event'
            - '@ssh.filemanager'
            - '@utility.process.builder'
            - '%timeout.push%'

    push.rsync.serverCommand:
        class: 'Hal\Agent\Push\Rsync\ServerCommand'
        arguments: ['@push.rsync.standard.remoter']

    push.rsync.standard.remoter:
        class: 'Hal\Agent\Remoting\SSHProcess'
        arguments:
            - '@logger.event'
            - '@ssh.manager'
            - '%timeout.push.serverCommand%'

    push.rsync.delta.remoter:
        class: 'Hal\Agent\Remoting\SSHProcess'
        arguments:
            - '@logger.event'
            - '@ssh.manager'
            - '%timeout.standard%'

    push.rsync.verify.remoter:
        class: 'Hal\Agent\Remoting\SSHProcess'
        arguments:
            - '@logger.event'
            - '@ssh.manager'
            - '%timeout.standard%'

    ####################################################################################################################
    # s3
    ####################################################################################################################

    push.s3.deployer:
        class: 'Hal\Agent\Push\S3\Deployer'
        arguments:
            - '@logger.event'
            - '@push.aws.authenticator'
            - '@push.s3.preparer'
            - '@push.s3.uploader'

    push.s3.preparer:
        class: 'Hal\Agent\Push\S3\Preparer'
        arguments:
            - '@logger.event'
            - '@utility.filesystem'
            - '@utility.process.builder'
            - '@push.mover'
            - '@push.packer'
            - '%timeout.filepacking%'

    push.s3.uploader:
        class: 'Hal\Agent\Push\S3\Uploader'
        arguments: ['@logger.event']

    ####################################################################################################################
    # codedeploy
    ####################################################################################################################

    push.cd.deployer:
        class: 'Hal\Agent\Push\CodeDeploy\Deployer'
        arguments:
            - '@logger.event'
            - '@push.aws.authenticator'
            - '@push.cd.healthchecker'
            - '@push.packer'
            - '@push.cd.uploader'
            - '@push.cd.pusher'

    push.cd.healthchecker:
        class: 'Hal\Agent\Push\CodeDeploy\HealthChecker'
        arguments:
            - '@clock'
            - '%date.timezone%'

    push.cd.uploader:
        class: 'Hal\Agent\Push\CodeDeploy\Uploader'
        arguments: ['@logger.event']
        calls:
            - ['allowOverwrite', [false]]

    push.cd.pusher:
        class: 'Hal\Agent\Push\CodeDeploy\Pusher'
        arguments:
            - '@logger.event'
            - '@push.cd.healthchecker'
            - '@push.cd.waiter'
            - '%hal.baseurl%'

    push.cd.waiter:
        class: 'Hal\Agent\Waiter\Waiter'
        arguments:
            - '%push.cd.waiter.interval%'
            - '%push.cd.waiter.max%'

    ####################################################################################################################
    # script
    ####################################################################################################################

    push.script.deployer:
        class: 'Hal\Agent\Push\Script\Deployer'
        arguments:
            - '@logger.event'
            - '@push.script.builder'

    push.script.builder:
        class: 'Hal\Agent\Push\Script\DeployDelegatingBuilder'
        arguments:
            - '@logger.event'
            - '@service_container'
            - '%deployment.script.platforms%'

    push.script.build.unix.handler:
        class: 'Hal\Agent\Build\Unix\UnixBuildHandler'
        arguments:
            - '@logger.event'
            - '@build.unix.exporter'
            - '@push.script.build.unix.builder'
            - '@build.unix.importer'
            - '@build.unix.cleaner'
            - '@encrypted.resolver'
            - '%build.platforms.option.docker.default_image%'

    push.script.build.unix.builder:
        parent: 'build.unix.builder'
        class: 'Hal\Agent\Push\Script\DeployDockerBuilder'

    ####################################################################################################################
    # private services used only by push actions
    ####################################################################################################################

    push.aws.authenticator:
        class: 'Hal\Agent\Push\AWSAuthenticator'
        arguments:
            - '@logger.event'
            - '@service_container'
            - '@aws'

    yaml.dumper:
        class: 'Symfony\Component\Yaml\Dumper'
        calls:
            - ['setIndentation', ['4']]
