language: php
php:
    - hhvm
    - 5.6
    - 5.5
    - 5.4

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer install --prefer-dist --dev
    - composer show --installed

script: vendor/bin/phpunit
