imports:
    - resource: '../vendor/ql/mcp-logger/config/config.php'
    - resource: '../vendor/hal/hal-core/config/config.php'
    - resource: 'services/*.yaml'
    - resource: 'services/*.php'

    - resource: 'services.yaml'
    - resource: 'parameters.yaml'

    - resource: 'hal.yaml'
      ignore_errors: true
