imports:
    - resource: '../vendor/hal/hal-core/config/*.yaml'
    - resource: 'vendor/*.yaml'
    - resource: 'services/*.yaml'

    - resource: 'services.yaml'
    - resource: 'parameters.yaml'

    - resource: 'hal.yaml'
      ignore_errors: true
