imports:
    - resource: '../vendor/hal/hal-core/config/config.yaml'
    - resource: 'vendor/*.yaml'
    - resource: 'services/*.yaml'

    - resource: 'services.yaml'
    - resource: 'parameters.yaml'
