parameters:
    ############################################################################
    # application
    ############################################################################
    application.id: '201359'
    application.title: 'Hal Agent'
    application.environment: '%env(ENVIRONMENT)%'

    application.major.version: '%env(HAL_APPLICATION_VERSION_MAJOR)%'
    application.minor.version: '%env(HAL_APPLICATION_VERSION_MINOR)%'
    application.version: '%application.major.version%.%application.minor.version%'

    application.sha: '%env(HAL_APPLICATION_SHA)%'

    hal.pushfile.path: '%root%/.hal9000.push.yml'

    ############################################################################
    # general
    ############################################################################
    root: '%env(HAL_ROOT)%'
    hal.baseurl: '%env(HAL_BASEURL)%'
    hal.api_token: '%env(HAL_API_TOKEN)%'

    unique.alphabet: '123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ'
    unique.size: 4
    date.timezone: 'America/Detroit'

    ############################################################################
    # paths
    ############################################################################
    path.archive: '%env(HAL_PATH_ARTIFACT_ARCHIVE)%'        # permanent filesystem artifact repository
    path.temp: '%env(HAL_PATH_BUILD_TEMP)%'                 # temporary scratch, local
    path.linux_builder: '%env(HAL_PATH_LINUX_BUILDER)%'     # temporary scratch, linux builder
    path.win_builder: '%env(HAL_PATH_WIN_BUILDER)%'         # temporary scratch, windows builder
    path.linux_dockerfiles: '%env(HAL_PATH_DOCKERFILES)%'

    ############################################################################
    # builders
    ############################################################################
    build.linux.user: '%env(HAL_LINUX_BUILDER_USER)%'
    build.linux.server: '%env(HAL_LINUX_BUILDER_SERVER)%'
    build.linux.keypath: '%env(HAL_LINUX_SSH_KEYPATH)%'

    build.windows.user: '%env(HAL_WIN_BUILDER_USER)%'
    build.windows.server: '%env(HAL_WIN_BUILDER_SERVER)%'
    build.windows.keypath: '%env(HAL_WIN_SSH_KEYPATH)%'

    deploy.rsync.user: '%env(HAL_RSYNC_DEPLOY_USER)%'
    deploy.rsync.keypath: '%env(HAL_RSYNC_SSH_KEYPATH)%'

    ############################################################################
    # logging
    ############################################################################
    error_handling.log_stacktrace: '%env(HAL_LOG_STACKTRACES_ON)%'
    error_handling.docker.debug: '%env(HAL_LOG_DOCKER_DEBUG_ON)%'

    ############################################################################
    # doctrine
    ############################################################################
    doctrine.user.service: 'doctrine.utility.lazy.user'

    ############################################################################
    # timeouts
    ############################################################################
    timeout.build: 1800
    timeout.push: 300

    timeout.push.build: 300
    timeout.push.serverCommand: 120

    timeout.standard: 20
    timeout.filepacking: 120
    timeout.filetransfer: 120

    push.cd.waiter.interval: 20
    push.cd.waiter.max: 60

    push.eb.waiter.interval: 20
    push.eb.waiter.max: 60

    build.ssm.waiter.interval: 30
    build.ssm.waiter.max: 60

    timeout.windows_builder_internal: 120

    ############################################################################
    # github
    ############################################################################
    github.token: '%env(HAL_GITHUB_ENTERPRISE_TOKEN)%'
    github.baseurl.site: '%env(HAL_GITHUB_ENTERPRISE_URL)%'
    github.baseurl.api: '%github.baseurl.site%/api/v3'

    ############################################################################
    # cache
    ############################################################################
    redis.server: '%env(HAL_REDIS_SERVER)%'
    redis.prefix: '%env(HAL_REDIS_PREFIX)%'

    cache.type.main: '%env(HAL_CACHE_MAIN)%'
    cache.type.github: '%env(HAL_CACHE_GITHUB)%'

    cache.github.default.ttl: 60
    cache.github.short.ttl: 20

    ############################################################################
    # windows platform
    ############################################################################

    build.windows_aws.build_path: '%env(HAL_WIN_AWS_BUILD_PATH)%'
    build.windows_aws.build_script_path: '%env(HAL_WIN_AWS_BUILD_SCRIPT_PATH)%'
    build.windows_aws.build_tools_path: '%env(HAL_WIN_AWS_BUILD_TOOLS_PATH)%'

    build.windows_aws.region: '%env(HAL_WIN_AWS_REGION)%'
    build.windows_aws.credential_name: '%env(HAL_WIN_AWS_CREDENTIAL)%'
    build.windows_aws.bucket: '%env(HAL_WIN_AWS_BUCKET)%'
    build.windows_aws.builder_filter: '%env(HAL_WIN_AWS_BUILDER_FILTER)%'

    ############################################################################
    # windows docker
    ############################################################################
    build.platforms.option.windows.docker_private_registry: '%env(HAL_WIN_DOCKER_PRIVATE_REG)%'
    build.platforms.option.windows.docker_easy_repo: '%env(HAL_DOCKER_EASY_REPO)%'
    build.platforms.option.windows.docker_default_image: '%build.platforms.option.windows.docker_private_registry%/hal-build-environments:vs2015'

    # "latest" also allows no tag
    build.platforms.option.windows.allowed_images:
        'microsoft/nanoserver':
            - 'latest'
            - '10.0.14393.1480'
            - '10.0.14393.1593'
        'microsoft/windowsservercore':
            - '10.0.14393.1480'
        '%build.platforms.option.windows.docker_private_registry%/hal-build-environments':
            - '*'

    build.platforms.option.manual_dns: '%env(HAL_DNS_INJECT_OPTIONS)%'

    ############################################################################
    # docker
    ############################################################################
    build.platforms.option.docker.source.repository: 'skluck/docker-images'
    build.platforms.option.docker.source.reference: 'master'

    build.platforms.option.docker.default_image: 'base_debian8'

    ############################################################################
    # credentials / encryption
    ############################################################################
    ssh.credentials:
        - ['%build.linux.user%',  '*', 'key:%build.linux.keypath%']
        - ['%deploy.rsync.user%', '*', 'key:%deploy.rsync.keypath%']

    encrypter.secret.path: '%env(HAL_CRYPTO_SECRETPATH)%'
    encrypter.publickey: '%env(HAL_CRYPTO_PUBLICKEY)%'
    encrypter.encryptedkey: '%env(HAL_CRYPTO_PRIVATEKEY)%'

    ############################################################################
    # platform modules
    ############################################################################

    build.platforms:
        linux: 'build.unix.handler'
        # windows: 'build.windows_aws_docker.handler'

    deployment.script.platforms:
        unix: 'push.script.build.unix.handler'

    deployment_before.build.platforms:
        unix: 'push.before.builder.unix_handler'
        windows: 'push.before.builder.windows_aws_docker.handler'
    deployment_after.build.platforms:
        unix: 'push.after.builder.unix_handler'
        windows: 'push.after.builder.windows_aws_docker.handler'

    deployment.platforms:
        rsync: 'push.rsync.deployer'
        eb: 'push.eb.deployer'
        s3: 'push.s3.deployer'
        cd: 'push.cd.deployer'
        script: 'push.script.deployer'

    deployment.script.platforms:
        linux: 'push.script.build.unix.handler'
        windows: 'push.script.build.windows_aws_docker.handler'

    push.s3.strategies:
        artifact: 'push.s3_artifact.deployer'
        sync: 'push.s3_sync.deployer'
