services:

    'Symfony\Component\Console\Application':
        public: true
        arguments:
            - '%application.title%'
            - '%application.version%'
        calls:
            - ['setDispatcher', ['@Symfony\Component\EventDispatcher\EventDispatcher']]
            - ['setCommandLoader', ['@Symfony\Component\Console\CommandLoader\ContainerCommandLoader']]

    'Symfony\Component\EventDispatcher\EventDispatcher':
        calls:
            - ['addSubscriber', ['@Hal\Agent\Symfony\ExceptionHandlerSubscriber']]

    'Symfony\Component\Console\CommandLoader\ContainerCommandLoader':
        - '@service_container'
        -
            'job:build':                'command.job.start_build'
            'job:release':              'command.job.start_deploy'
            'management:build:remove':  'command.management.remove_build'
            'runner:build':             'command.job.run_build'
            'runner:deploy':            'command.job.run_deploy'

    ####################################################################################################################
    # utility / shared
    ####################################################################################################################

    'QL\MCP\Common\Clock':
        - 'now'
        - 'UTC'

    'Symfony\Component\Yaml\Parser': []

    'Hal\Agent\Symfony\ProcessRunner':
        - '@Hal\Agent\Logger\EventLogger'

    'Symfony\Component\Filesystem\Filesystem': []

    ####################################################################################################################
    # job configuration
    ####################################################################################################################

    'Hal\Agent\JobConfiguration\ConfigurationReader':
        - '@Hal\Agent\Logger\EventLogger'
        - '@Symfony\Component\Filesystem\Filesystem'
        - '@Symfony\Component\Yaml\Parser'
        - '%configuration.files%'

    'Hal\Agent\JobConfiguration\StepParser': []
