parameters:
    debug: false

    github.token: ''
    github.com.token: ''

    hal.baseurl: 'http://hal9000/'

    # file path to store permanent archives of builds                   | recommended path: 'PROJECT_DIRECTORY/.archive'
    environment.archive: ''

    # temporary scratch
    environment.temp: '%build.unix.temp%'

    ############################################################################
    # UNIX BUILDING
    ############################################################################

    # system PATH inherited by build scripts
    build.unix.path: ''

    # system HOME inherited by build scripts
    # Leave this empty to use the system temporary directory            | recommended path: 'PROJECT_DIRECTORY/.build/home'
    build.unix.home: ''

    # temporary storage for build and push artifacts
    # Leave this empty to use the system temporary directory            | recommended path: 'PROJECT_DIRECTORY/.build'
    build.unix.temp: ''

    ############################################################################
    # WINDOWS BUILDING
    ############################################################################

    # user used to SSH and RSYNC to target servers
    build.windows.remoteUser: ''
    build.windows.server: ''

    # temporary storage for windows build artifacts
    # Leave this empty to use a subdirectory in the remote users HOME   | recommended path: '/cygdrive/c/builds'
    build.windows.temp: ''

    ############################################################################
    # PUSHING
    ############################################################################

    push.rsync.remoteUser: ''

    aws.region: ''
    aws.s3.builds: ''
    aws.ec2.user: 'ec2-user'

    ############################################################################
    # DATABASE / NOTIFICATIONS
    ############################################################################

    # Core logger service hostname
    # Only required in standalone installations
    logger.mcp.host: 'http://qlsonictest:2581/web/core/logentries'

    # doctrine configuration
    doctrine.connection:
        driver:     pdo_mysql
        host:       localhost
        user:       root
        password:
        dbname:     hal
    doctrine.devmode: true

    email.from.name: 'HAL9000 - DEV'
    email.notify:
        - 'yourname@quickenloans.com'

    ############################################################################
    # CREDENTIALS
    ############################################################################

    ssh.credentials:
        - [%build.windows.remoteUser%, '*', '/path/to/id_rsa']
        - [%push.rsync.remoteUser%, '*', '/path/to/id_rsa']
        - [%aws.ec2.user%, '*', '']

    # dont ever commit, dont be stupid
    aws.credentials.key: ''
    aws.credentials.secret: ''
