parameters:
    debug: false

    github.token: ''
    github.baseurl: 'http://git/api/v3/'
    github.com.token: ''

    hal.baseurl: 'http://hal9000/'

    # file path to store permanent archives of builds
    environment.archive: '/builds/hal9000'

    # temporary scratch
    environment.temp: '%build.unix.temp%'

    ############################################################################
    # UNIX BUILDING
    ############################################################################

    # system PATH inherited by build scripts
    build.unix.path: '/usr/local/zend/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin'

    # system HOME inherited by build scripts
    # Leave this empty to use the system temporary directory
    build.unix.home: '/var/spool/hal9000/home'

    # temporary storage for build and push artifacts
    # Leave this empty to use the system temporary directory
    build.unix.temp: '/var/spool/hal9000'

    ############################################################################
    # WINDOWS BUILDING
    ############################################################################

    # user used to SSH and RSYNC to target servers
    build.windows.remoteUser: ''
    build.windows.server: ''

    # temporary storage for windows build artifacts
    # Leave this empty to use a subdirectory in the remote users HOME
    build.windows.temp: ''

    ############################################################################
    # PUSHING
    ############################################################################

    push.rsync.remoteUser: ''

    aws.region: ''
    aws.s3.builds: ''
    aws.ec2.user: 'ec2-user'

    ############################################################################
    # DATABASE / NOTIFICATIONS
    ############################################################################

    # Core logger service hostname
    # Only required in standalone installations
    logger.mcp.host: 'http://qlsonicprod:2581/web/core/logentries'

    # doctrine configuration
    doctrine.devmode: false
    doctrine.connection:
        driver: pdo_mysql
        host: prod.example.com
        user: placeholder
        password: placeholder
        dbname: hal9000

    ############################################################################
    # CREDENTIALS
    ############################################################################

    ssh.credentials:
        - [%build.windows.remoteUser%, '*', '/path/to/id_rsa']
        - [%push.rsync.remoteUser%, '*', '/path/to/id_rsa']
        - [%aws.ec2.user%, '*', '']

    aws.credentials.key: ''
    aws.credentials.secret: ''
