parameters:
    debug: false

    github.token: ''
    github.baseurl: 'http://git/api/v3/'
    github.com.token: ''

    hal.baseurl: 'http://hal9000/'

    # system PATH inherited by build scripts
    environment.path: '/usr/local/zend/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin'

    # system HOME inherited by build scripts
    # Leave this empty to use the system temporary directory
    environment.home: '/var/spool/hal9000/home'

    # temporary storage for build and push artifacts
    # Leave this empty to use the system temporary directory
    environment.temp: '/var/spool/hal9000'

    # file path to store permanent archives of builds
    environment.archive: '/builds/hal9000'

    # user used to SSH and RSYNC to target servers
    push.sshUser: ''

    # Core logger service hostname
    # Only required in standalone installations
    logger.mcp.host: 'http://qlsonicprod:2581/web/core/logentries'

    # doctrine configuration
    doctrine.devmode: false
    doctrine.connection:
        driver: pdo_mysql
        host: prod.example.com
        user: placeholder
        password: placeholder
        dbname: hal9000





    aws.region: ''
    aws.s3.builds: ''


    aws.credentials.key: ''
    aws.credentials.secret: ''
