imports:
    - resource: ../vendor/ql/hal-core/config/di.yml
    - resource: di.yml
    - resource: di.logging.yml
    - resource: parameters.yml
    - resource: config.env.yml

parameters:
    application.name: 'HAL 9000 Agent'
    application.version: '2.0.0'
    application.id: '200947'
