parameters:
    email.server: 'mail.example.com'
    email.notify:
        - 'hal@example.com'
    email.from: 'hal@example.com'
    email.from.name: 'HAL9000'

    email.reply: 'hal@example.com'

    timeout.build: 1200
    timeout.push: 300

    timeout.push.build: 300
    timeout.push.ec2: 300

    timeout.push.serverCommand: 120

    timeout.standard: 20
    timeout.filepacking: 120
    timeout.filetransfer: 120

    push.cd.waiter.interval: 20
    push.cd.waiter.max: 60

    push.eb.waiter.interval: 20
    push.eb.waiter.max: 60

    github.baseurl.site: 'http://git/'
    github.baseurl.api: 'http://git/api/v3/'

    docker.source.repository: 'skluck/docker-images'
    docker.source.reference: 'master'
    docker.source.path: '/docker-images'
    docker.default.image: 'legacy'
    docker.option.sudo: false
    docker.option.debug: false

    aws.ec2.user: 'ec2-user'

    # Replaced by env
    database.username: ''
    database.server: ''
    database.database: ''

    doctrine.connection:
        driver: pdo_mysql
        host: '%database.server%'
        user: '%database.username%'
        password: '%database.password%'
        dbname: '%database.database%'
