parameters:

    clock.timezone: 'America/Detroit'

    ############################################################################
    # timeouts
    ############################################################################

    timeout.build: 1800
    timeout.push: 300

    timeout.push.build: 300

    timeout.push.serverCommand: 120

    timeout.standard: 20
    timeout.filepacking: 120
    timeout.filetransfer: 120

    push.cd.waiter.interval: 20
    push.cd.waiter.max: 60

    push.eb.waiter.interval: 20
    push.eb.waiter.max: 60

    ############################################################################
    # github
    ############################################################################

    github.baseurl.site: 'http://git'
    github.baseurl.api: 'http://git/api/v3'

    ############################################################################
    # docker
    ############################################################################

    docker.source.repository: 'skluck/docker-images'
    docker.source.reference: 'master'
    docker.source.path: '/docker-images'
    docker.default.image: 'legacy'
    docker.option.sudo: false
    docker.option.debug: false

    ############################################################################
    # error handling and logging
    ############################################################################

    logging.stacktrace: true

    mcp.logger.service.syslog.options:
        ident: 'hal-%application.id%'
        facility: !php/const:LOG_USER
    mcp.logger.service.errorlog.options:
        type: 3
        facility: !php/const:QL\MCP\Logger\Service\ErrorLogService::FILE
        file: '../.error.log'
    mcp.logger.default_properties:
        applicationID: '%application.id%'

    ############################################################################
    # database
    ############################################################################

    # Replaced by env
    database.username: ''
    database.server: ''
    database.database: ''

    doctrine.connection:
        driver: pdo_mysql
        host: '%database.server%'
        user: '%database.username%'
        password: '%database.password%'
        dbname: '%database.database%'
