hal_core:
    proxy_dir: '.doctrine'

    cache:
        type: 'predis'
        predis_service_id: 'redis'
        lvl2_enabled: true
        lvl2_ttl: 600
        lvl2_lock: 60

    clock:
        service_id: 'clock'

    event_listeners:
        prePersist: ['doctrine.listener.persist']

mcp_logger:
    syslog_options:
        ident: 'hal-%application.id%'
        facility: 'LOG_USER'
        silent: true
        options: ['LOG_ODELAY', 'LOG_CONS']

    errorlog_options:
        type: !php/const:QL\MCP\Logger\Service\ErrorLogService::FILE
        destination: '../.error.log'

    default_properties:
        applicationID: '%application.id%'
        serverEnvironment: '%application.environment%'

parameters:
    application.environment: ''
    clock.timezone: 'America/Detroit'

    ############################################################################
    # timeouts
    ############################################################################

    timeout.build: 1800
    timeout.push: 300

    timeout.push.build: 300

    timeout.push.serverCommand: 120

    timeout.standard: 20
    timeout.filepacking: 120
    timeout.filetransfer: 120

    push.cd.waiter.interval: 20
    push.cd.waiter.max: 60

    push.eb.waiter.interval: 20
    push.eb.waiter.max: 60

    ############################################################################
    # github
    ############################################################################

    github.baseurl.site: 'http://git'
    github.baseurl.api: '%github.baseurl.site%/api/v3'

    ############################################################################
    # docker
    ############################################################################

    docker.source.repository: 'skluck/docker-images'
    docker.source.reference: 'master'
    docker.source.path: '/docker-images'
    docker.default.image: 'legacy'
    docker.option.sudo: false
    docker.option.debug: false

    ############################################################################
    # error handling
    ############################################################################

    logging.stacktrace: true
