parameters:
    github.token: ''

    # system PATH inherited by build scripts
    environment.path: ''

    # system HOME inherited by build scripts
    # Leave this empty to use the system temporary directory
    environment.home: ''

    # temporary storage for build and push artifacts
    # Leave this empty to use the system temporary directory
    environment.temp: ''

    # file path to store permanent archives of builds
    environment.archive: ''

    # user used to SSH and RSYNC to target servers
    ssh-user: ''

    # Core logger service hostname
    mcp-logger.host: 'qlsonictest'
