# Standalone installation only

parameters:
    github.token: ''
    github.baseurl: 'http://git/api/v3/'
    github.com.token: ''

    # system PATH inherited by build scripts
    agent.environment.path: '/usr/local/zend/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin'

    # system HOME inherited by build scripts
    # Leave this empty to use the system temporary directory
    agent.environment.home: '/var/spool/hal9000test/home'

    # temporary storage for build and push artifacts
    # Leave this empty to use the system temporary directory
    agent.environment.temp: '/var/spool/hal9000test'

    # file path to store permanent archives of builds
    agent.environment.archive: ''

    # user used to SSH and RSYNC to target servers
    agent.ssh-user: ''

    # Core logger service hostname
    # Only required in standalone installations
    agent.logger.mcp.host: 'http://qlsonictest:2581/web/core/logentries'

    # doctrine configuration
    doctrine.connection:
        driver:     pdo_mysql
        host:       localhost
        user:       root
        password:
        dbname:     hal
    doctrine.devmode: true
