imports:
    - resource: ../vendor/ql/hal-core/config/hal-core.yml
    - resource: di.yml
    - resource: config.global.yml
    - resource: config.env.yml

parameters:
    application.id: '200947'
    application.name: 'HAL 9000 Agent'

    application.major.version: '2'
    application.minor.version: '3'
    application.version: '%application.major.version%.%application.minor.version%.0'

    # base58
    unique.alphabet: '123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ'
    unique.size: 4
