imports:
    - resource: '../vendor/ql/hal-core/configuration/hal-core.yml'
    - resource: '../vendor/ql/mcp-logger/configuration/mcp-logger.yml'
    - resource: 'di.yml'
    - resource: 'config.global.yml'
    - resource: 'config.env.yml'

parameters:
    application.id: '201359'
    application.name: 'Hal Agent'

    application.major.version: '3'
    application.version: '3.0.0'

    # base58
    unique.alphabet: '123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ'
    unique.size: 4
