parameters:
    email.server: 'mail.example.com'
    email.notify:
        - 'hal@example.com'
    email.from: 'hal@example.com'
    email.from.name: 'HAL9000'

    email.reply: 'hal@example.com'

    timeout.build: 900
    timeout.push: 300

    timeout.push.build: 300
    timeout.push.ec2: 300

    timeout.push.serverCommand: 120

    timeout.standard: 20
    timeout.filepacking: 120
    timeout.filetransfer: 120

    github.baseurl.site: 'http://git/'

    aws.region: ''
    aws.s3.builds: ''
    aws.ec2.user: ''

    aws.credentials.key: ''
    aws.credentials.secret: ''
