imports:
    - resource: ../vendor/ql/hal-core/config/di.yml
    - resource: di.yml
    - resource: di.command.yml
    - resource: di.build.yml
    - resource: di.push.yml
    - resource: di.logging.yml
    - resource: config.global.yml
    - resource: config.env.yml

parameters:
    application.id: '200947'
    application.name: 'HAL 9000 Agent'

    application.major.version: '2'
    application.version: '%application.major.version%.0.0'

    # base58
    unique.alphabet: '123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ'
    unique.size: 4
