imports:
    -
        resource: ../vendor/ql/hal-core/config/di.yml
    -
        resource: di.yml
    -
        resource: parameters.yml
    -
        resource: config.env.yml

parameters:
    application.name: 'HAL 9000 Agent'
    application.version: '1.0.1'
    application.id: '200947'
