parameters:
    email.server: 'mail.example.com'
    email.notify:
        - 'hal@example.com'
    email.from: 'hal@example.com'
    email.from.name: 'HAL9000'

    email.reply: 'hal@example.com'

    timeout.build: 600
    timeout.push: 300
    timeout.push.serverCommand: 300
    timeout.push.build: 300

    timeout.filepacking: 120

    github.baseurl.site: 'http://git/'
